const actiontype = {
    // PLUS_ORDER: 'PLUS_ORDER',
    // MINUS_ORDER: 'MINUS_ORDER',
    // VALUE_CHANGE: 'VALUE_CHANGE',
    // LOADING: 'LOADING_CHANGE',
    // LOGIN: 'LOGIN_CHANGE',
    // USER: 'USER_CHANGE',
    // NOTES: 'NOTES_CHANGE',
    // NOTES2: 'NOTES2_CHANGE',
    // ORDERGRAB: 'ORDER_GRAB',
    // STATUSGRABUSER: 'STATUS_GRAB_USER',
    // MENUWHAT: 'MENU_WHAT',
    // MIDTRANS:'ORDER_MIDTRANS'
    MENUSEKARANG: 'MENU_SEKARANG',
    ORDERLIST: 'ORDER_LIST',
    ORDERPRICE: 'ORDER_PRICE',
    DATAUSER: 'DATA_USER',
}

export default actiontype;